M48
; DRILL file {KiCad 7.0.2} date Wed Jun 21 18:27:06 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-21T18:27:06-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0748
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1339
%
G90
G05
T1
X6.2662Y-3.1465
X6.2662Y-3.374
T2
X4.9783Y-2.2205
X4.9783Y-2.6535
X5.6476Y-2.2205
X5.6476Y-2.6535
T3
X4.9783Y-2.437
X5.6476Y-2.437
T0
M30
